# Generated by Django 6.1 on 2026-08-07 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrackBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('posicao_inicio_x', models.FloatField()),
                ('posicao_fim_x', models.FloatField()),
                ('ocupado', models.BooleanField(default=False)),
                ('trem_ocupante', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Bloco de Via',
                'verbose_name_plural': 'Blocos de Via',
                'ordering': ['posicao_inicio_x'],
            },
        ),
    ]
