# Generated by Django 6.1 on 2026-08-07 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Switch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('posicao_x', models.FloatField()),
                ('posicao_y', models.FloatField(default=150)),
                ('estado', models.CharField(choices=[('reto', 'Reto'), ('desviado', 'Desviado')], default='reto', max_length=10)),
            ],
            options={
                'verbose_name': 'AMV',
                'verbose_name_plural': 'AMVs',
                'ordering': ['posicao_x'],
            },
        ),
    ]
