# Generated by Django 6.1 on 2026-08-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_switch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('origem_x', models.FloatField()),
                ('origem_y', models.FloatField(default=150)),
                ('velocidade_px_ms', models.FloatField(default=0.0513)),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_movimento', 'Em Movimento'), ('parado', 'Parado (bloqueado)'), ('chegou', 'Chegou ao Destino')], default='aguardando', max_length=15)),
            ],
            options={
                'verbose_name': 'Trem',
                'verbose_name_plural': 'Trens',
                'ordering': ['codigo'],
            },
        ),
    ]
