# Generated by Django 6.1 on 2026-08-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_train'),
    ]

    operations = [
        migrations.AddField(
            model_name='train',
            name='destino',
            field=models.CharField(choices=[('B', 'Estação B'), ('C', 'Estação C')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='train',
            name='origem_x',
            field=models.FloatField(default=100),
        ),
    ]
