# Generated by Django 6.1 on 2026-08-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_train_destino_alter_train_origem_x'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackblock',
            name='linha',
            field=models.CharField(choices=[('linha1', 'Linha Superior'), ('linha2', 'Linha Inferior')], default='linha1', max_length=10),
        ),
    ]
