# Generated by Django 6.1 on 2026-08-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_trackblock_linha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackblock',
            name='linha',
        ),
        migrations.AddField(
            model_name='trackblock',
            name='posicao_y',
            field=models.FloatField(default=100.0),
        ),
    ]
